services:
  db:
    image: mysql:8.0
    container_name: WerwolfIQ
    environment:
      MYSQL_ROOT_PASSWORD: geheim                # ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: WerwolfIQ                      # Initial database name
    ports:
      - "3306:3306"  # Expose MySQL on port 3306


volumes:
  db_data:  # Define the named volume for persistent data
